# Generated by Django 4.2.3 on 2023-08-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('postid', models.AutoField(primary_key=True, serialize=False)),
                ('postdescription', models.TextField()),
                ('postprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('postcount', models.PositiveIntegerField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
