# Generated by Django 4.2.3 on 2023-08-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paymentid',
            new_name='payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='planid',
            new_name='plan_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='userid',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
