# Generated by Django 4.2.3 on 2023-08-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_rename_paymentid_payment_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
    ]
