# Generated by Django 4.1.7 on 2023-08-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterdetails',
            name='phonenumber',
            field=models.CharField(default='', max_length=20),
        ),
    ]
