# Generated by Django 4.1.7 on 2023-08-13 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Recruiter', '0002_recruiterdetails_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
