# Generated by Django 4.2.3 on 2023-08-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0005_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterdetails',
            name='district',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
