# Generated by Django 4.2.3 on 2023-08-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0007_jobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterdetails',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
    ]
