# Generated by Django 4.2.3 on 2023-08-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0008_alter_recruiterdetails_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterdetails',
            name='companyregno',
            field=models.CharField(max_length=100),
        ),
    ]
