# Generated by Django 4.2.3 on 2023-09-01 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Recruiter', '0009_alter_recruiterdetails_companyregno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reject', 'Reject'), ('interview', 'Interview'), ('shortlisted', 'Shortlisted'), ('selected', 'Selected')], default='applied', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recruiter.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
