# Generated by Django 4.2.3 on 2023-09-02 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0010_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='companyid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Recruiter.recruiterdetails'),
            preserve_default=False,
        ),
    ]
