# Generated by Django 4.2.3 on 2023-09-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0011_applicants_companyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicants',
            old_name='companyid',
            new_name='company',
        ),
    ]
