# Generated by Django 4.2.3 on 2023-09-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0013_remove_applicants_company_applicants_companyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterdetails',
            name='companyregno',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
