# Generated by Django 4.2.3 on 2023-08-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_customuser_email_verified_customuser_otp_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_secret',
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
