# Generated by Django 4.2.3 on 2023-08-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
