# Generated by Django 4.2.3 on 2023-08-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_alter_userdetails_expected_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
