# Generated by Django 4.2.3 on 2023-09-16 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0014_alter_recruiterdetails_companyregno'),
        ('User', '0014_userfollowscompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoreJobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignorepostid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recruiter.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
